
import os
import hashlib
import requests
from bitcoinutils.setup import setup
from dotenv import load_dotenv
from bitcoinutils.keys import PrivateKey, P2trAddress
from bitcoinutils.script import Script
from bitcoinutils.transactions import Transaction, TxInput, TxOutput, TxWitnessInput



setup("testnet")
load_dotenv()
MEMPOOL_API_URL = "https://mempool.space/testnet/api/"
FEE= 100 # Satoshis
DUST_LIMIT=300  # Satoshis


# Load Sender internal private key from environment 
sender_private_key = PrivateKey(os.getenv("SENDER_PRIVATE_KEY_WIF"))
sender_pubkey = sender_private_key.get_public_key()
print(f"Sender Public Key: {sender_pubkey.to_hex()}")

# Load Receiver internal private key from environment
receiver_private_key = PrivateKey(os.getenv("RECEIVER_PRIVATE_KEY_WIF"))
receiver_pubkey = receiver_private_key.get_public_key()
print(f"Receiver Public Key: {receiver_pubkey.to_hex()}")

# sender address Generation Function
def sender_address(sender_pubkey):
    """
    Generates the sender Taproot address from the given public key.

    Parameters
    ----------
    sender_pubkey : PublicKey
        The public key of the sender.

    Returns
    -------
    sender_addr_obj : P2trAddress
        The sender Taproot address object.
    sender_addr_str : str
        The sender Taproot address string.
    """
    try:
        sender_addr_obj = sender_pubkey.get_taproot_address()
        sender_addr_str = sender_addr_obj.to_string()
        return sender_addr_obj, sender_addr_str
    except Exception as e:
        print(f"Error creating address: {e}")


# Generate Asset ID Function
def generate_asset_id(asset_metadata, genesis_outpoint, asset_tag):
    """
    Generates the asset ID from the given asset metadata, genesis outpoint, and asset tag.

    The asset ID is generated by concatenating the asset metadata, genesis outpoint, and asset tag, and then taking the SHA-256 hash of the resulting string.

    Parameters
    ----------
    asset_metadata : str
        The asset metadata.
    genesis_outpoint : str
        The genesis outpoint of the asset.
    asset_tag : str
        The asset tag.

    Returns
    -------
    asset_id : bytes

        The generated asset ID.
    """
    asset_data = f"{asset_metadata}|{genesis_outpoint}|{asset_tag}".encode()
    asset_id = hashlib.sha256(asset_data).digest()
    return asset_id

# generate Receiver address from asset id
def receiver_address(asset_id):
    """
    Generates the receiver Taproot address from the given asset ID.

    Parameters
    ----------
    asset_id : bytes
        The asset ID.

    Returns
    -------
    receiver_addr_obj : TaprootAddress
        The receiver Taproot address object.
    receiver_addr_str : str
        The receiver Taproot address string.
    """
    try:
        priv_asset_key = PrivateKey(b=asset_id)
        pub_asset_key = priv_asset_key.get_public_key()
        tr_asset_script = Script([pub_asset_key.to_x_only_hex(), 'OP_1'])
        receiver_add_obj = pub_asset_key.get_taproot_address(tr_asset_script)
        receiver_add_str = receiver_add_obj.to_string()
        return receiver_add_obj, receiver_add_str
    except Exception as e:
        print(f"Error creating address: {e}")
        return None

# Create transactions 
def create_transaction(utxos, receiver_addr_str, amount, sender_add_str, sender_private_key:PrivateKey):
    """
    Creates a transaction from the given UTXOs, receiver address, amount, sender address, and sender private key.

    Parameters
    ----------
    utxos : list
        List of UTXOs to be used as inputs for the transaction.
    receiver_addr_str : str
        The Taproot address of the receiver.
    amount : int
        The amount of sats to be transferred.
    sender_add_str : str
        The Taproot address of the sender.
        The private key of the sender.

    Returns
    -------
    Transaction
        The created transaction.

    Raises
    ------
    ValueError
        If the total value of the UTXOs is less than the amount to be transferred plus the fee.
    Exception
        If there is an error in creating the transaction.
    """
    try:
        tx_ins = []
        values = []
        # Create inputs
        for utxo in utxos:
            txin = TxInput(utxo['txid'], utxo['vout'])
            tx_ins.append(txin)
            total += utxo['value']
            values.append(utxo['value'])
            if total >= amount + FEE:
                break
        print(f"Total Input Amount: {total} sats")
        print(values)
        # Check funds
        if total < amount + FEE:
            raise ValueError("Insufficient funds")
        
        # Create outputs
        tx_outs = [TxOutput(amount - FEE, P2trAddress(receiver_addr_str).to_script_pub_key())]

        # Create transaction
        tx = Transaction(tx_ins, tx_outs, has_segwit=True)

        # Sign inputs
        sig = sender_private_key.sign_taproot_input(
            tx, 0,
            utxo_scripts=[P2trAddress(sender_add_str).to_script_pub_key()],
            amounts=values,
        )
        tx.witnesses.append(TxWitnessInput([sig]))

        print(f"Signed TX: {tx.serialize()}")
        broadcast(tx.serialize())
        return tx

    except Exception as e:
        print(f"Error in key-path spend: {e}")

# fetch UTXOs from Mempool API
def fetch_utxos(address):
    """
    Fetches UTXOs from Mempool API for the given address.

    Parameters
    ----------
    address : str
        The Taproot address for which to fetch UTXOs.

    Returns
    -------
    list
        A list of UTXOs for the given address.

    Raises
    ------
    Exception
        If there is an error in fetching the UTXOs.
    """
    url = f"{MEMPOOL_API_URL}/address/{address}/utxo"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print("Error fetching UTXOs:", response.status_code)
        return []

# broadcast transaction to Mempool API
def broadcast(raw_tx):
    """
    Broadcasts a raw transaction to the Mempool API.

    Parameters
    ----------
    raw_tx : str
        The raw transaction to broadcast.

    Returns
    -------
    None

    Raises
    ------
    Exception
        If there is an error in broadcasting the transaction.
    """
    try:
        resp = requests.post(f"{MEMPOOL_API_URL}/tx", data=raw_tx, headers={"Content-Type": "text/plain"})
        if resp.status_code == 200:
            print(f"TX Broadcasted: {resp.text}")
        else:
            print(f"Broadcast error {resp.status_code}: {resp.text}")
    except Exception as e:
        print(f"Error broadcasting: {e}")

def main():
    """
    Main entry point for the script.

    Prints the Taproot asset transfer over the bitcoin layer 1, generates the sender Taproot address,
    fetches UTXOs for the generated Taproot address, generates an asset ID, generates the receiver Taproot
    address, and creates a transaction.

    Parameters
    ----------
    None

    Returns
    -------
    None
    """
    print("\n===============================")
    print("Taproot Asset Transfer over the bitcoin layer 1")

    
    # Generate sender Taproot address
    sender_addr_obj, sender_add_str = sender_address(sender_pubkey)
    print(f"Sender Taproot Address: {sender_add_str}")

    # Fetch UTXOs for the generated Taproot address
    utxos = fetch_utxos(sender_add_str)
    print(f"Fetched UTXOs: {utxos}")
    if not utxos:
        print("No UTXOs found for the Taproot address.")
        return

    print("===============================\n")
    asset_id = generate_asset_id("HelloWorld", f"{utxos[0]['txid']}:{utxos[0]['vout']}", "TAG001")
    print(f"Generated Asset ID: {asset_id.hex()}")

    # Receiver address generation
    receiver_add_obj, receiver_add_str = receiver_address(asset_id)
    print(f"Receiver Taproot Address: {receiver_add_str}")
    print("===============================")
    
    # Create transaction
    amount = int(input("Enter amount in sats to send: "))
    create_transaction(utxos, receiver_add_str, amount, sender_add_str, sender_private_key)
    

    
if __name__ == "__main__":
    main()

